name: app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  
  intl: ^0.19.0
  flutter_modular: ^6.3.4
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  iconsax: ^0.0.8
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
